AllCops:
  TargetRubyVersion: 2.4
Lint/UriEscapeUnescape:
  Enabled: false
Metrics/AbcSize:
  Max: 22
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Max: 25
Metrics/PerceivedComplexity:
  Max: 9
